package com.ethan.web.webmvc.dao;

import java.io.Serializable;

import javax.persistence.*;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@ApiModel
@Table(name="tab_user")
public class UserEntity implements Serializable {
    /**
     * generated by addFieldComment 1
     * 
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id")
    @ApiModelProperty(value="")
    private Integer id;

    /**
     * generated by addFieldComment 1
     * 
     */
    @Column(name="user")
    @ApiModelProperty(value="")
    private String user;

    /**
     * generated by addFieldComment 1
     * 
     */
    @Column(name="age")
    @ApiModelProperty(value="")
    private Integer age;

    /**
     * generated by addFieldComment 1
     * 
     */
    @Column(name="account")
    @ApiModelProperty(value="")
    private String account;

    /**
     * generated by addFieldComment 1
     * 
     */
    @Column(name="passworld")
    @ApiModelProperty(value="")
    private String passworld;

    /**
     * generated by addFieldComment 2
     * tab_user
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassworld() {
        return passworld;
    }

    public void setPassworld(String passworld) {
        this.passworld = passworld;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", user=").append(user);
        sb.append(", age=").append(age);
        sb.append(", account=").append(account);
        sb.append(", passworld=").append(passworld);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserEntity other = (UserEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUser() == null ? other.getUser() == null : this.getUser().equals(other.getUser()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getAccount() == null ? other.getAccount() == null : this.getAccount().equals(other.getAccount()))
            && (this.getPassworld() == null ? other.getPassworld() == null : this.getPassworld().equals(other.getPassworld()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUser() == null) ? 0 : getUser().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getAccount() == null) ? 0 : getAccount().hashCode());
        result = prime * result + ((getPassworld() == null) ? 0 : getPassworld().hashCode());
        return result;
    }
}