package com.ethan.web.webmvc.dao;

import java.io.Serializable;

import javax.persistence.*;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@ApiModel
@Table(name="tab_data_dictionary")
public class AdArticleEntity implements Serializable {
    /**
     * generated by addFieldComment 1
     * 
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="dd_id")
    @ApiModelProperty(value="")
    private Integer ddId;

    /**
     * generated by addFieldComment 1
     * 
     */
    @Column(name="dd_type_code")
    @ApiModelProperty(value="")
    private Integer ddTypeCode;

    /**
     * generated by addFieldComment 1
     * 
     */
    @Column(name="dd_code")
    @ApiModelProperty(value="")
    private Integer ddCode;

    /**
     * generated by addFieldComment 1
     * 
     */
    @Column(name="dd_name")
    @ApiModelProperty(value="")
    private String ddName;

    /**
     * generated by addFieldComment 1
     * 
     */
    @Column(name="dd_description")
    @ApiModelProperty(value="")
    private String ddDescription;

    /**
     * generated by addFieldComment 1
     * 
     */
    @Column(name="dd_expand")
    @ApiModelProperty(value="")
    private String ddExpand;

    /**
     * generated by addFieldComment 2
     * tab_data_dictionary
     */
    private static final long serialVersionUID = 1L;

    public Integer getDdId() {
        return ddId;
    }

    public void setDdId(Integer ddId) {
        this.ddId = ddId;
    }

    public Integer getDdTypeCode() {
        return ddTypeCode;
    }

    public void setDdTypeCode(Integer ddTypeCode) {
        this.ddTypeCode = ddTypeCode;
    }

    public Integer getDdCode() {
        return ddCode;
    }

    public void setDdCode(Integer ddCode) {
        this.ddCode = ddCode;
    }

    public String getDdName() {
        return ddName;
    }

    public void setDdName(String ddName) {
        this.ddName = ddName;
    }

    public String getDdDescription() {
        return ddDescription;
    }

    public void setDdDescription(String ddDescription) {
        this.ddDescription = ddDescription;
    }

    public String getDdExpand() {
        return ddExpand;
    }

    public void setDdExpand(String ddExpand) {
        this.ddExpand = ddExpand;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ddId=").append(ddId);
        sb.append(", ddTypeCode=").append(ddTypeCode);
        sb.append(", ddCode=").append(ddCode);
        sb.append(", ddName=").append(ddName);
        sb.append(", ddDescription=").append(ddDescription);
        sb.append(", ddExpand=").append(ddExpand);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdArticleEntity other = (AdArticleEntity) that;
        return (this.getDdId() == null ? other.getDdId() == null : this.getDdId().equals(other.getDdId()))
            && (this.getDdTypeCode() == null ? other.getDdTypeCode() == null : this.getDdTypeCode().equals(other.getDdTypeCode()))
            && (this.getDdCode() == null ? other.getDdCode() == null : this.getDdCode().equals(other.getDdCode()))
            && (this.getDdName() == null ? other.getDdName() == null : this.getDdName().equals(other.getDdName()))
            && (this.getDdDescription() == null ? other.getDdDescription() == null : this.getDdDescription().equals(other.getDdDescription()))
            && (this.getDdExpand() == null ? other.getDdExpand() == null : this.getDdExpand().equals(other.getDdExpand()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDdId() == null) ? 0 : getDdId().hashCode());
        result = prime * result + ((getDdTypeCode() == null) ? 0 : getDdTypeCode().hashCode());
        result = prime * result + ((getDdCode() == null) ? 0 : getDdCode().hashCode());
        result = prime * result + ((getDdName() == null) ? 0 : getDdName().hashCode());
        result = prime * result + ((getDdDescription() == null) ? 0 : getDdDescription().hashCode());
        result = prime * result + ((getDdExpand() == null) ? 0 : getDdExpand().hashCode());
        return result;
    }
}